- 1.1.13
- _NAME: Multi Device Silent Mouse M585/M590
  _modelId: B01B406B0000
  _sensitive: {persistent-remappable-keys: true}
  _serial: D9811C87
  _unitId: 6E98090A
  _wpid: 406B
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 91: 0, 93: 0}
  lowres-scroll-mode: false
  persistent-remappable-keys: null
  pointer_speed: 256
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 91: 91, 93: 93}
- _NAME: LIFT
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting,
    fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures,
    gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B03100000000
  _sensitive: {divert-keys: false, dpi: false, reprogrammable-keys: false}
  _serial: EE415445
  _unitId: EE415445
  _wpid: B031
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 253: 0}
  dpi: 1600
  lowres-scroll-mode: false
  reprogrammable-keys: {82: 82, 83: 83, 86: 86, 253: 253}
