# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#1c1c1c'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#cf8282'
green   = '#5fd7af'
yellow  = '#c5c575'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#a1c5a5'
white   = '#ebdbb2'

