
[font]
size = 10.0
normal = { family = "JetBrains Mono" }

[general]
import = [
  "~/.config/alacritty/themes/vscode_dark.toml"
  # "~/.config/alacritty/themes/gruvbox_dark.toml"
  # "~/.config/alacritty/themes/gruvbox_light.toml"
]

[terminal]

[terminal.shell]
program = "tmux"
